#!/bin/bash

certbotinstall() {
    local os
    read -r -p "Select an operating system, debian or rhel: " os

    case "$os" in
        rhel)
            echo "### Begin rhel Install ###"
            yum install epel-release -y &&
                yum upgrade -y &&
                yum install snapd -y || return 1
            systemctl enable --now snapd.socket || return 1
            ln -sfn /var/lib/snapd/snap /snap || return 1
            snap install --classic certbot || return 1
            ln -sfn /snap/bin/certbot /usr/bin/certbot || return 1
            echo "### rhel Install Complete ###"
            ;;
        debian)
            echo "### Begin debian Install ###"
            apt -y update && apt -y install snapd || return 1
            snap install core || return 1
            systemctl enable --now snapd.socket || return 1
            ln -sfn /var/lib/snapd/snap /snap || return 1
            snap install --classic certbot || return 1
            ln -sfn /snap/bin/certbot /usr/bin/certbot || return 1
            echo "### debian Install Complete ###"
            ;;
        *)
            echo "You selected something besides debian or rhel."
            return 1
            ;;
    esac
}

newcert() {
    local fqdn
    read -r -p "What is the fully qualified domain name? " fqdn
    if [[ -z "$fqdn" ]]; then
        echo "A domain name is required."
        return 1
    fi

    service nginx stop || return 1
    certbot certonly --standalone --agree-tos --no-eff-email \
        -m corey.zelinski@ieee.org -d "$fqdn"
    local certbot_status=$?
    service nginx start || return 1
    return "$certbot_status"
}

renewcerts() {
    service nginx stop || return 1
    certbot renew
    local certbot_status=$?
    service nginx start || return 1
    return "$certbot_status"
}
